name = "zyrex-api"
main = "workers/api.js"
compatibility_date = "2024-12-01"

# Environment variables
[vars]
DISCORD_CLIENT_ID = "1519456130290417776"
DISCORD_REDIRECT_URI = "https://zyrexediting.xyz/api/auth/callback"
GUILD_ID = "1518954946110685184"
UPLOAD_ROLE_ID = "1519624224476762122"

# Secrets (set via wrangler secret put):
# DISCORD_CLIENT_SECRET
# DISCORD_BOT_TOKEN

# R2 Bucket bindings
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "zyrexediting"

[[r2_buckets]]
binding = "STORAGE_PROD"
bucket_name = "zyrexediting-staging"

# === Routes ===
# Route - handles /api/* and dl subdomain and thumbnail subdomain
[[routes]]
pattern = "zyrexediting.xyz/resources*"
zone_id = "1844c05896c2b3897c61d37dc08b71e8"

[[routes]]
pattern = "zyrexediting.xyz/api/*"
zone_id = "1844c05896c2b3897c61d37dc08b71e8"

[[routes]]
pattern = "dl.zyrexediting.xyz/*"
zone_id = "1844c05896c2b3897c61d37dc08b71e8"

[[routes]]
pattern = "thumbnail.zyrexediting.xyz/*"
zone_id = "1844c05896c2b3897c61d37dc08b71e8"
